# Configuration file for unit test runner.
language: php
php:
  - 5.3
  - 5.4
  - 5.5
env:
  - PHPUNIT_ARGS=--group=sass
before_script:
  - composer self-update
  - composer install --no-interaction --prefer-dist --dev
script: php tests/lint.php tests/ lib/ && phpunit --verbose $PHPUNIT_ARGS
notifications:
  email: false
